import type { Metadata } from 'next';
import { Noto_Sans_Bengali } from 'next/font/google';
import './globals.css';
import Navber from '@/shared/Navber';
import Marquees from '@/components/Marquee';
import Footer from '@/shared/Footer';
import { Toaster } from 'react-hot-toast';
import 'react-loading-skeleton/dist/skeleton.css';

const noto_Sans_Bengali = Noto_Sans_Bengali({
  subsets: ['latin', 'bengali'],
});

export const metadata: Metadata = {
  title: 'বাজার দর — আজকের দাঁড়ির দাম',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${noto_Sans_Bengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navber />
        <Marquees />
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
